import { NextRequest, NextResponse } from "next/server"
import { youtubeAuth } from "@/lib/youtube-auth"

// Disable body parsing for file uploads
export const config = {
  api: {
    bodyParser: false,
  },
}

export async function POST(req: NextRequest) {
  try {
    // Get the access token from the Authorization header
    const authHeader = req.headers.get("Authorization")
    if (!authHeader?.startsWith("Bearer ")) {
      return NextResponse.json({ error: "Missing or invalid authorization" }, { status: 401 })
    }

    // Parse form data to get video file and metadata
    const formData = await req.formData()
    const videoFile = formData.get("video") as File | null
    const title = formData.get("title") as string
    const description = formData.get("description") as string
    const tagsString = formData.get("tags") as string
    const privacyStatus = formData.get("privacyStatus") as "public" | "private" | "unlisted" || "public"
    const categoryId = formData.get("categoryId") as string

    if (!videoFile) {
      return NextResponse.json({ error: "Video file is required" }, { status: 400 })
    }

    if (!title) {
      return NextResponse.json({ error: "Title is required" }, { status: 400 })
    }

    // Parse tags from JSON string or use defaults
    let tags: string[] = []
    try {
      tags = tagsString ? JSON.parse(tagsString) : []
    } catch {
      tags = tagsString ? [tagsString] : []
    }

    // Initialize YouTube auth with the token from header
    const token = authHeader.replace("Bearer ", "")
    
    // Create a temporary YouTubeAuth instance with the provided token
    const tempYoutubeAuth = new YouTubeAuthWithToken(token)

    // Convert File to Blob
    const videoBlob = new Blob([await videoFile.arrayBuffer()], { type: videoFile.type })

    // Upload to YouTube
    const result = await tempYoutubeAuth.uploadVideo(videoBlob, {
      title: title.substring(0, 100), // YouTube title max 100 chars
      description: description || "Generated by YouTubeAuto.ai",
      tags: tags.slice(0, 15), // YouTube allows max 15 tags
      categoryId: categoryId || "22",
      privacyStatus,
    })

    return NextResponse.json({
      success: true,
      videoId: result.videoId,
      url: result.url,
      message: `Video uploaded successfully! View at: ${result.url}`,
    })
  } catch (error: any) {
    console.error("YouTube upload API error:", error)
    return NextResponse.json(
      { error: error.message || "Failed to upload video" },
      { status: 500 }
    )
  }
}

// Helper class to use with a provided token
class YouTubeAuthWithToken {
  private accessToken: string

  constructor(token: string) {
    this.accessToken = token
  }

  async uploadVideo(
    videoBlob: Blob,
    metadata: {
      title: string
      description: string
      tags: string[]
      categoryId?: string
      privacyStatus: "public" | "private" | "unlisted"
    }
  ): Promise<{ videoId: string; url: string }> {
    const boundary = "-------314159265358979323846"
    const delimiter = `\r\n--${boundary}\r\n`
    const closeDelimiter = `\r\n--${boundary}--`

    const metadataPart =
      delimiter +
      "Content-Type: application/json; charset=UTF-8\r\n\r\n" +
      JSON.stringify({
        snippet: {
          title: metadata.title,
          description: metadata.description,
          tags: metadata.tags,
          categoryId: metadata.categoryId || "22",
        },
        status: {
          privacyStatus: metadata.privacyStatus,
          selfDeclaredMadeForKids: false,
        },
      })

    const videoArrayBuffer = await videoBlob.arrayBuffer()
    const videoBytes = new Uint8Array(videoArrayBuffer)

    const videoPart = delimiter + "Content-Type: video/*\r\n\r\n"

    const requestBody = new Blob([metadataPart, videoPart, videoBytes, closeDelimiter])

    const response = await fetch(
      `https://www.googleapis.com/upload/youtube/v3/videos?uploadType=multipart&part=snippet,status`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${this.accessToken}`,
          "Content-Type": `multipart/related; boundary="${boundary}"`,
        },
        body: requestBody,
      }
    )

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}))
      throw new Error(errorData.error?.message || `Upload failed (${response.status})`)
    }

    const data = await response.json()
    return {
      videoId: data.id,
      url: `https://www.youtube.com/watch?v=${data.id}`,
    }
  }
}
