import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { getValidAccessToken } from "@/lib/youtube-token";
import { statSync, existsSync, createReadStream } from "fs";
import { mkdir, writeFile } from "fs/promises";
import path from "path";

export const maxDuration = 600;
export const dynamic = "force-dynamic";

export async function POST(request) {
  try {
    const cookieStore = await cookies();
    let accessToken, newToken;
    try {
      const result = await getValidAccessToken(cookieStore);
      accessToken = result.accessToken;
      newToken = result.newToken;
    } catch (err) {
      if (err.message === "NOT_CONNECTED") return NextResponse.json({ error: "YouTube not connected" }, { status: 401 });
      throw err;
    }

    const { videoUrl, title, description, tags, categoryId, privacyStatus, scheduledTime, language } = await request.json();
    if (!videoUrl || !title) return NextResponse.json({ error: "videoUrl and title required" }, { status: 400 });

    const localPath = videoUrl.replace(/https?:\/\/[^\/]+/, "").replace("/storage/", "");
    const filePath = path.join(process.cwd(), "storage", localPath);
    
    if (!existsSync(filePath)) return NextResponse.json({ error: "Video file missing on server." }, { status: 404 });

    const videoSize = statSync(filePath).size;
    console.log("Starting Memory-Safe upload for size:", (videoSize/1024/1024).toFixed(2), "MB");

    const videoMetadata = {
      snippet: {
        title: title.slice(0, 100),
        description: (description || "Generated by YouTubeAuto.ai") + "\n\n#viral #trending",
        tags: tags ? tags.slice(0, 15) : [],
        categoryId: categoryId || "22",
        defaultLanguage: language || "hi",
      },
      status: { privacyStatus: scheduledTime ? "private" : (privacyStatus || "private"), selfDeclaredMadeForKids: false },
    };
    if (scheduledTime) videoMetadata.status.publishAt = new Date(scheduledTime).toISOString();

    const initResponse = await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status", {
      method: "POST",
      headers: {
        Authorization: "Bearer " + accessToken,
        "Content-Type": "application/json",
        "X-Upload-Content-Type": "video/mp4",
        "X-Upload-Content-Length": videoSize.toString(),
      },
      body: JSON.stringify(videoMetadata),
      signal: AbortSignal.timeout(30000),
    });

    if (!initResponse.ok) {
      const errData = await initResponse.json().catch(() => ({}));
      const errReason = errData?.error?.errors?.[0]?.reason || "";
      if (errReason === "uploadLimitExceeded" || initResponse.status === 400) {
        const queueDir = path.join(process.cwd(), "storage", "ready_to_upload");
        if (!existsSync(queueDir)) await mkdir(queueDir, { recursive: true });
        const queueFile = path.join(queueDir, `queued_${Date.now()}.json`);
        await writeFile(queueFile, JSON.stringify({ videoUrl, title, description, tags, categoryId, privacyStatus, scheduledTime, language, queuedAt: new Date().toISOString() }));
        return NextResponse.json({ success: true, queued: true, message: "YouTube Quota full. Queued locally for 24hrs." });
      }
      throw new Error(JSON.stringify(errData));
    }

    const uploadUrl = initResponse.headers.get("Location");
    if (!uploadUrl) throw new Error("No upload URL received");

    // RAM SAFE: Node Stream -> Readable Web Stream for fetch
    const fileStream = createReadStream(filePath, { highWaterMark: 1 * 1024 * 1024 });
    const iterator = fileStream[Symbol.asyncIterator]();
    const stream = new ReadableStream({
      async pull(controller) {
        const { value, done } = await iterator.next();
        if (done) { controller.close(); } else { controller.enqueue(value); }
      }
    });

    const uploadResponse = await fetch(uploadUrl, {
      method: "PUT",
      headers: { "Content-Type": "video/mp4", "Content-Length": videoSize.toString() },
      body: stream,
      duplex: 'half' // Required for Node 18+ streams in fetch
    });

    if (!uploadResponse.ok) {
        const errText = await uploadResponse.text();
        throw new Error("Upload Stream failed: " + errText);
    }
    const uploadedVideo = await uploadResponse.json();

    // Auto cleanup temp files after upload
    try {
      const { unlink } = await import("fs/promises")
      const tempFiles = [filePath.replace("videos/", "temp/video_") ]
      // Clean ASS subtitles older than 1hr
      const { readdir } = await import("fs/promises")
      const subsDir = path.join(process.cwd(), "storage", "subtitles")
      const subFiles = await readdir(subsDir).catch(() => [])
      for (const f of subFiles) {
        const fp = path.join(subsDir, f)
        try { const s = statSync(fp); if (Date.now() - s.mtimeMs > 3600000) await unlink(fp) } catch {}
      }
      console.log("🧹 Cleanup done")
    } catch {}

    const finalResponse = NextResponse.json({
      success: true, videoId: uploadedVideo.id,
      youtubeUrl: "https://www.youtube.com/watch?v=" + uploadedVideo.id,
      status: uploadedVideo.status ? uploadedVideo.status.privacyStatus : "private",
    });
    if (newToken) finalResponse.cookies.set("yt_access_token", newToken, { httpOnly: true, maxAge: 3600, path: "/", sameSite: "lax" });
    return finalResponse;
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

