import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { getValidAccessToken } from "@/lib/youtube-token";
import { readFile } from "fs/promises";
import { existsSync } from "fs";
import path from "path";

export const maxDuration = 600; // ✅ 10 min (was 300 — not enough for large files)
export const dynamic = "force-dynamic";

export async function POST(request) {
  try {
    const cookieStore = await cookies();
    let accessToken, newToken;
    try {
      const result = await getValidAccessToken(cookieStore);
      accessToken = result.accessToken;
      newToken = result.newToken;
    } catch (err) {
      if (err.message === "NOT_CONNECTED") {
        return NextResponse.json({ error: "YouTube connected nahi hai" }, { status: 401 });
      }
      throw err;
    }

    const { videoUrl, title, description, tags, categoryId, privacyStatus, scheduledTime, language } = await request.json();
    if (!videoUrl || !title) {
      return NextResponse.json({ error: "videoUrl aur title required hain" }, { status: 400 });
    }

    // Read video file
    let videoBuffer;
    const localPath = videoUrl.replace(/https?:\/\/[^\/]+/, "").replace("/storage/", "");
    const filePath = path.join(process.cwd(), "storage", localPath);
    console.log("Video file:", filePath, "exists:", existsSync(filePath));

    if (existsSync(filePath)) {
      videoBuffer = await readFile(filePath);
      console.log("Video size:", (videoBuffer.length / 1024 / 1024).toFixed(2) + "MB");
    } else {
      const videoResponse = await fetch(videoUrl, { signal: AbortSignal.timeout(60000) });
      if (!videoResponse.ok) throw new Error("Video fetch failed: " + videoUrl);
      videoBuffer = Buffer.from(await videoResponse.arrayBuffer());
    }

    const videoSize = videoBuffer.length;

    const videoMetadata = {
      snippet: {
        title: title.slice(0, 100),
        description: (description || "Generated by YouTubeAuto.ai") + "\n\n#viral #trending #youtube",
        tags: tags ? tags.slice(0, 15) : [],
        categoryId: categoryId || "22",
        defaultLanguage: language || "hi",
      },
      status: {
        privacyStatus: scheduledTime ? "private" : (privacyStatus || "private"),
        selfDeclaredMadeForKids: false,
      },
    };

    if (scheduledTime) {
      videoMetadata.status.publishAt = new Date(scheduledTime).toISOString();
    }

    // Init resumable upload
    console.log("Starting resumable upload, size:", videoSize);
    const initResponse = await fetch(
      "https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",
      {
        method: "POST",
        headers: {
          Authorization: "Bearer " + accessToken,
          "Content-Type": "application/json",
          "X-Upload-Content-Type": "video/mp4",
          "X-Upload-Content-Length": videoSize.toString(),
        },
        body: JSON.stringify(videoMetadata),
        signal: AbortSignal.timeout(30000),
      }
    );

    if (!initResponse.ok) {
      const e = await initResponse.json();
      console.error("Init upload failed - status:", initResponse.status, JSON.stringify(e));
      throw new Error(JSON.stringify(e));
    }

    const uploadUrl = initResponse.headers.get("Location");
    console.log("Upload URL received");
    if (!uploadUrl) throw new Error("No upload URL received");

    // ✅ FIX: 1MB chunks instead of 5MB — prevents timeout on slow connections
    // YouTube minimum chunk size is 256KB, we use 1MB for reliability
    const CHUNK_SIZE = 1 * 1024 * 1024;
    let offset = 0;
    let uploadedVideo = null;

    while (offset < videoSize) {
      const end = Math.min(offset + CHUNK_SIZE, videoSize);
      const chunk = videoBuffer.subarray(offset, end);
      const percent = ((offset / videoSize) * 100).toFixed(1);
      console.log(`Chunk ${percent}% -- bytes ${offset}-${end - 1}/${videoSize}`);

      let chunkSuccess = false;
      for (let attempt = 1; attempt <= 5; attempt++) { // ✅ 5 retries (was 3)
        try {
          const uploadResponse = await fetch(uploadUrl, {
            method: "PUT",
            headers: {
              "Content-Type": "video/mp4",
              "Content-Length": chunk.length.toString(),
              "Content-Range": `bytes ${offset}-${end - 1}/${videoSize}`,
            },
            body: chunk,
            signal: AbortSignal.timeout(120000), // ✅ 2 min per chunk (was 5 min total — caused confusion)
          });

          if (end === videoSize && (uploadResponse.status === 200 || uploadResponse.status === 201)) {
            uploadedVideo = await uploadResponse.json();
            console.log("YouTube upload success! Video ID:", uploadedVideo.id);
            chunkSuccess = true;
            offset = videoSize;
            break;
          } else if (uploadResponse.status === 308) {
            // Resume Incomplete — YouTube tells us where to continue from
            const range = uploadResponse.headers.get("Range");
            if (range) {
              offset = parseInt(range.split("-")[1]) + 1;
            } else {
              offset = end;
            }
            chunkSuccess = true;
            break;
          } else if (uploadResponse.status === 200 || uploadResponse.status === 201) {
            // Sometimes YouTube returns 200 before last chunk
            uploadedVideo = await uploadResponse.json();
            console.log("YouTube upload success! Video ID:", uploadedVideo.id);
            chunkSuccess = true;
            offset = videoSize;
            break;
          } else if (!uploadResponse.ok) {
            const errText = await uploadResponse.text();
            throw new Error("Chunk upload failed: " + errText);
          } else {
            offset = end;
            chunkSuccess = true;
            break;
          }
        } catch (chunkErr) {
          console.log(`Chunk attempt ${attempt} failed:`, chunkErr.message);
          if (attempt === 5) throw chunkErr;
          // ✅ Exponential backoff: 3s, 6s, 12s, 24s
          await new Promise(r => setTimeout(r, 3000 * attempt));
        }
      }

      if (!chunkSuccess) break;
    }

    if (!uploadedVideo) throw new Error("Upload completed but no video data");

    console.log("✅ YouTube upload complete:", uploadedVideo.id);

    const finalResponse = NextResponse.json({
      success: true,
      videoId: uploadedVideo.id, // ✅ Added videoId to response
      youtubeUrl: "https://www.youtube.com/watch?v=" + uploadedVideo.id,
      status: uploadedVideo.status ? uploadedVideo.status.privacyStatus : "private",
    });

    if (newToken) {
      finalResponse.cookies.set("yt_access_token", newToken, {
        httpOnly: true, maxAge: 3600, path: "/", sameSite: "lax",
      });
    }

    return finalResponse;
  } catch (error) {
    console.error("YouTube upload error:", error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}