import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { getValidAccessToken } from "@/lib/youtube-token";
import { readFile } from "fs/promises";
import { existsSync } from "fs";
import path from "path";

export async function POST(request) {
  try {
    const cookieStore = await cookies();
    let accessToken;
    try {
      const result = await getValidAccessToken(cookieStore);
      accessToken = result.accessToken;
    } catch (err) {
      if (err.message === "NOT_CONNECTED") return NextResponse.json({ error: "YouTube connected nahi hai" }, { status: 401 });
      throw err;
    }

    const { videoUrl, title, description, tags, categoryId, privacyStatus, scheduledTime, language } = await request.json();
    if (!videoUrl || !title) return NextResponse.json({ error: "videoUrl aur title required hain" }, { status: 400 });

    // Local file seedha read karo
    let videoBytes;
    const localPath = videoUrl.replace("http://localhost:3000", "").replace("/storage/", "");
    const filePath = path.join(process.cwd(), "storage", localPath);
    console.log("Video file:", filePath, "exists:", existsSync(filePath));

    if (existsSync(filePath)) {
      const buffer = await readFile(filePath);
      videoBytes = new Uint8Array(buffer);
      console.log("✅ Video file read! Size:", videoBytes.length);
    } else {
      const videoResponse = await fetch(videoUrl);
      if (!videoResponse.ok) throw new Error("Video fetch failed: " + videoUrl);
      const buffer = await videoResponse.arrayBuffer();
      videoBytes = new Uint8Array(buffer);
    }

    const videoMetadata = {
      snippet: {
        title: title.slice(0, 100),
        description: (description || "Generated by YouTubeAuto.ai") + "\n\n#shorts #viral #trending",
        tags: tags?.slice(0, 15) || [],
        categoryId: categoryId || "22",
        defaultLanguage: language || "hi"
      },
      status: {
        privacyStatus: scheduledTime ? "private" : (privacyStatus || "private"),
        selfDeclaredMadeForKids: false,
        ...(scheduledTime ? { publishAt: new Date(scheduledTime).toISOString() } : {})
      }
    };

    const initResponse = await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
        "X-Upload-Content-Type": "video/mp4",
        "X-Upload-Content-Length": videoBytes.length.toString()
      },
      body: JSON.stringify(videoMetadata),
    });

    if (!initResponse.ok) {
      const e = await initResponse.json();
      console.error("Init upload failed:", e);
      throw new Error(JSON.stringify(e));
    }

    const uploadUrl = initResponse.headers.get("Location");
    console.log("Upload URL:", uploadUrl ? "✅ Got it" : "❌ Missing");

    const uploadResponse = await fetch(uploadUrl, {
      method: "PUT",
      headers: { "Content-Type": "video/mp4", "Content-Length": videoBytes.length.toString() },
      body: videoBytes
    });

    if (!uploadResponse.ok) {
      const e = await uploadResponse.text();
      throw new Error("Upload failed: " + e);
    }

    const uploaded = await uploadResponse.json();
    console.log("✅ YouTube upload success! Video ID:", uploaded.id);

    return NextResponse.json({
      success: true,
      videoId: uploaded.id,
      youtubeUrl: `https://www.youtube.com/watch?v=${uploaded.id}`,
      status: uploaded.status?.privacyStatus
    });
  } catch (error) {
    console.error("YouTube upload error:", error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
